insert into tblkullanici (ad, soyad, adres, il) values ('Abbey', 'Normansell', '17th Floor', 'Babakansari');
insert into tblkullanici (ad, soyad, adres, il) values ('Angelle', 'Pernell', 'Suite 47', 'Maralik');
insert into tblkullanici (ad, soyad, adres, il) values ('Blondelle', 'Lydden', '6th Floor', 'Sang-e Chārak');
insert into tblkullanici (ad, soyad, adres, il) values ('Bibbie', 'Wiltshear', 'Suite 71', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Margaux', 'Castagna', 'Room 1425', 'Toulouse');
insert into tblkullanici (ad, soyad, adres, il) values ('Lotte', 'Beckinsall', 'Suite 36', 'Tarvasjoki');
insert into tblkullanici (ad, soyad, adres, il) values ('Thacher', 'Telega', 'Apt 1850', 'Banaba');
insert into tblkullanici (ad, soyad, adres, il) values ('Grier', 'Pauncefoot', '6th Floor', 'Zhengmo');
insert into tblkullanici (ad, soyad, adres, il) values ('Odilia', 'Murdy', 'Apt 528', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Eadie', 'Charleston', 'PO Box 95928', 'Asker');
insert into tblkullanici (ad, soyad, adres, il) values ('Courtenay', 'Moggle', 'Suite 27', 'Siguinon');
insert into tblkullanici (ad, soyad, adres, il) values ('Therese', 'Merriment', 'PO Box 83937', 'Nanmu');
insert into tblkullanici (ad, soyad, adres, il) values ('Cami', 'Feehely', '1st Floor', 'Guanban');
insert into tblkullanici (ad, soyad, adres, il) values ('Noe', 'Gadie', 'Suite 89', 'Rockford');
insert into tblkullanici (ad, soyad, adres, il) values ('Adelheid', 'Callum', 'PO Box 381', 'Springfield');
insert into tblkullanici (ad, soyad, adres, il) values ('Karlis', 'Panswick', 'Apt 643', 'Springfield');
insert into tblkullanici (ad, soyad, adres, il) values ('Ric', 'Elesander', 'Apt 1085', 'Shuangnian');
insert into tblkullanici (ad, soyad, adres, il) values ('Crissie', 'Bachelar', '15th Floor', 'Casa Nova');
insert into tblkullanici (ad, soyad, adres, il) values ('Sacha', 'Ryde', 'Suite 88', 'Zhonghualu');
insert into tblkullanici (ad, soyad, adres, il) values ('Hildy', 'Hamilton', 'PO Box 6553', 'Labrador');
insert into tblkullanici (ad, soyad, adres, il) values ('Jehu', 'Boughen', 'Room 659', 'Xilópolis');
insert into tblkullanici (ad, soyad, adres, il) values ('Mona', 'Turmall', 'PO Box 50714', 'Kostrzyn nad Odrą');
insert into tblkullanici (ad, soyad, adres, il) values ('Darlleen', 'McFadyen', '10th Floor', 'Jutiapa');
insert into tblkullanici (ad, soyad, adres, il) values ('Farlay', 'Round', '1st Floor', 'Changhan');
insert into tblkullanici (ad, soyad, adres, il) values ('Annabela', 'Gooderson', '4th Floor', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Hodge', 'Kinde', null, 'Shijak');
insert into tblkullanici (ad, soyad, adres, il) values ('Tabor', 'Goold', 'Room 1939', 'Cognac');
insert into tblkullanici (ad, soyad, adres, il) values ('Mirna', 'Benmore', '20th Floor', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Mathew', 'Hubery', 'PO Box 93406', 'Mayahi');
insert into tblkullanici (ad, soyad, adres, il) values ('Joli', 'Godson', 'PO Box 8014', 'Strasbourg');
insert into tblkullanici (ad, soyad, adres, il) values ('Wendall', 'Rosekilly', 'Suite 81', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Gisella', 'Gaythwaite', null, 'Penghua');
insert into tblkullanici (ad, soyad, adres, il) values ('Pepi', 'Bowkett', '6th Floor', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Berton', 'Caddy', 'Suite 73', 'Cusapín');
insert into tblkullanici (ad, soyad, adres, il) values ('Alphonse', 'Leadbeatter', 'Suite 17', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Tybi', 'Sposito', 'Suite 39', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Mel', 'Brearley', 'PO Box 83408', 'Kaz');
insert into tblkullanici (ad, soyad, adres, il) values ('Delilah', 'Grioli', null, 'Iza');
insert into tblkullanici (ad, soyad, adres, il) values ('Benni', 'Grayston', '1st Floor', 'Wotan');
insert into tblkullanici (ad, soyad, adres, il) values ('Stillmann', 'Silveston', 'Apt 657', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Phylis', 'Nanson', 'Apt 1155', 'Zhonghe');
insert into tblkullanici (ad, soyad, adres, il) values ('Mignon', 'Kear', 'Apt 473', 'Drochia');
insert into tblkullanici (ad, soyad, adres, il) values ('Barnett', 'Dei', 'Apt 1980', 'Rukunlima Bawah');
insert into tblkullanici (ad, soyad, adres, il) values ('Salvidor', 'Jenken', 'Apt 1164', 'Turenki');
insert into tblkullanici (ad, soyad, adres, il) values ('Catina', 'Linwood', 'PO Box 7768', 'Salamanca');
insert into tblkullanici (ad, soyad, adres, il) values ('Revkah', 'Dmitrievski', 'Suite 69', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Rachele', 'Lukesch', 'Suite 20', 'Saryaghash');
insert into tblkullanici (ad, soyad, adres, il) values ('Brynne', 'Mancktelow', 'PO Box 43164', 'Łobżenica');
insert into tblkullanici (ad, soyad, adres, il) values ('Arluene', 'Klimpt', 'Room 300', 'Olinda');
insert into tblkullanici (ad, soyad, adres, il) values ('Alvan', 'Autin', 'PO Box 32940', 'Barobo');
insert into tblkullanici (ad, soyad, adres, il) values ('Bernadene', 'Renac', 'Room 1348', 'Västervik');
insert into tblkullanici (ad, soyad, adres, il) values ('Ber', 'Dennes', 'Suite 16', 'Timbó');
insert into tblkullanici (ad, soyad, adres, il) values ('Gregory', 'McCoy', 'Apt 1334', 'Wangying');
insert into tblkullanici (ad, soyad, adres, il) values ('Jeremy', 'Danielsky', 'Suite 61', 'Nuwara Eliya');
insert into tblkullanici (ad, soyad, adres, il) values ('Laryssa', 'Caplan', 'Room 1394', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Eadie', 'Pock', '7th Floor', 'Kotor');
insert into tblkullanici (ad, soyad, adres, il) values ('Hobart', 'Cusworth', 'Suite 16', 'Chlumec');
insert into tblkullanici (ad, soyad, adres, il) values ('Rennie', 'Prendergrass', 'Suite 2', 'Zhutang');
insert into tblkullanici (ad, soyad, adres, il) values ('Fidela', 'Povlsen', null, 'Estefania');
insert into tblkullanici (ad, soyad, adres, il) values ('Giovanna', 'MacCallum', 'PO Box 69218', 'Rey');
insert into tblkullanici (ad, soyad, adres, il) values ('Cooper', 'Risbrough', 'Apt 401', 'Lameiro');
insert into tblkullanici (ad, soyad, adres, il) values ('Sigismondo', 'Merrell', null, 'Hekou');
insert into tblkullanici (ad, soyad, adres, il) values ('Gerty', 'Balfour', 'Room 408', 'Crossmolina');
insert into tblkullanici (ad, soyad, adres, il) values ('Agace', 'Dymoke', 'Suite 17', 'Egvekinot');
insert into tblkullanici (ad, soyad, adres, il) values ('Ernaline', 'Hrishchenko', 'Suite 21', 'Göteborg');
insert into tblkullanici (ad, soyad, adres, il) values ('Meaghan', 'Wynter', 'Room 1841', 'Banjar Kawan');
insert into tblkullanici (ad, soyad, adres, il) values ('Anne-marie', 'Ishaki', 'Suite 30', 'Tsurib');
insert into tblkullanici (ad, soyad, adres, il) values ('Pepe', 'Rudgerd', 'Room 816', 'Dongchen');
insert into tblkullanici (ad, soyad, adres, il) values ('Consolata', 'Whetton', 'Apt 1852', 'Paujiles');
insert into tblkullanici (ad, soyad, adres, il) values ('Garwood', 'Baynton', '13th Floor', 'Sumurber');
insert into tblkullanici (ad, soyad, adres, il) values ('Felicia', 'Appleyard', 'Suite 84', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Margette', 'Arthey', 'Apt 218', 'Daxindian');
insert into tblkullanici (ad, soyad, adres, il) values ('Artie', 'Catcherside', 'PO Box 50266', 'Si Racha');
insert into tblkullanici (ad, soyad, adres, il) values ('Cammie', 'Vitte', 'PO Box 60329', 'Nasielsk');
insert into tblkullanici (ad, soyad, adres, il) values ('Nani', 'De Matteis', 'PO Box 17870', 'Mosfilotí');
insert into tblkullanici (ad, soyad, adres, il) values ('Cesya', 'Panting', 'Suite 36', 'Quintães');
insert into tblkullanici (ad, soyad, adres, il) values ('Erasmus', 'Oels', 'PO Box 86795', 'Ust’-Uda');
insert into tblkullanici (ad, soyad, adres, il) values ('Petunia', 'Hairyes', 'Room 836', 'Kudamatsu');
insert into tblkullanici (ad, soyad, adres, il) values ('Merrill', 'Petroff', 'Apt 650', 'Podhum');
insert into tblkullanici (ad, soyad, adres, il) values ('Donelle', 'Nicholls', 'Room 6', 'Bibinje');
insert into tblkullanici (ad, soyad, adres, il) values ('Nicol', 'Hazeman', 'PO Box 44411', 'Balabag');
insert into tblkullanici (ad, soyad, adres, il) values ('Sibella', 'Duny', 'Room 1596', 'Rongmei');
insert into tblkullanici (ad, soyad, adres, il) values ('Putnam', 'Ballintime', '6th Floor', 'Karanyowka');
insert into tblkullanici (ad, soyad, adres, il) values ('Tuesday', 'Dumbelton', 'Room 1676', 'Chybie');
insert into tblkullanici (ad, soyad, adres, il) values ('Jean', 'Valentinetti', 'Suite 85', 'Zavolzh’ye');
insert into tblkullanici (ad, soyad, adres, il) values ('Tallulah', 'Beminster', 'Suite 30', 'Chacapalpa');
insert into tblkullanici (ad, soyad, adres, il) values ('Lilas', 'Faragher', '20th Floor', 'Guanyang');
insert into tblkullanici (ad, soyad, adres, il) values ('Hendrick', 'Julyan', '11th Floor', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Alaster', 'Hailey', '5th Floor', 'Tembladera');
insert into tblkullanici (ad, soyad, adres, il) values ('Park', 'Barney', '19th Floor', 'Houping');
insert into tblkullanici (ad, soyad, adres, il) values ('Jackqueline', 'Roote', 'PO Box 93847', 'Mairana');
insert into tblkullanici (ad, soyad, adres, il) values ('Ximenes', 'Harlock', 'Room 1199', null);
insert into tblkullanici (ad, soyad, adres, il) values ('Gunther', 'Mewrcik', 'Apt 1440', 'Wates');
insert into tblkullanici (ad, soyad, adres, il) values ('Vance', 'Adne', 'Apt 1566', 'Thạnh Mỹ');
insert into tblkullanici (ad, soyad, adres, il) values ('Marlane', 'Kleinbaum', 'Room 538', 'Carreira');
insert into tblkullanici (ad, soyad, adres, il) values ('Kermie', 'Bulleyn', 'Apt 1079', 'Lubochnia');
insert into tblkullanici (ad, soyad, adres, il) values ('Porter', 'McCrostie', 'PO Box 45280', 'Marinilla');
insert into tblkullanici (ad, soyad, adres, il) values ('Daniele', 'Raeside', 'Suite 94', 'Kamyzyak');
insert into tblkullanici (ad, soyad, adres, il) values ('June', 'Ragborne', 'Room 313', 'Daoukro');
insert into tblkullanici (ad, soyad, adres, il) values ('Allyn', 'Chattock', 'Suite 59', 'Mỹ Xuyên');